### ISSUE TITLE
License-File

### ISSUE THREAD

**Issue by ahoiroman** [viruzx/Sitemap-Generator-Crawler#10]
Please add a LICENSE-File.

**Comment by vezaynk** [comment]
I have long considered how to license this. No license on github equates to "All Rights Reserved". Despite that, I had portions of my code-base ripped-off without credit (Not going to point fingers at anybody).

I have no legal team, and either it doesn't matter. I have no way of enforcing being credited without counting on the goodwill of users who will either credit, or not credit me in spite of whatever license I put.

Hence, I will _legally_ publish it under good ol' MIT.
