### ISSUE TITLE
Does not work with the following website address...

### ISSUE THREAD

**Issue by duongkyvuong** [viruzx/Sitemap-Generator-Crawler#100]
Does not work with the following website address: https://satrafoods.com.vn/
![err](https://github.com/vezaynk/Sitemap-Generator-Crawler/assets/158221613/f2a9c644-867b-45ec-a442-36c8686ad7ab)

**Comment by vezaynk** [comment]
It looks like `https://satrafoods.com.vn/vn/vn/vn/vn/.../vn/san-pham` are pages that exist in your website (probably by mistake). It's a bug in the website, not this script.
