### ISSUE TITLE
How to setup page I need ?

### ISSUE THREAD

**Issue by nethiker76** [viruzx/Sitemap-Generator-Crawler#101]
Scanning large websites takes a lot of time, and if it is interrupted, there will be no data (sitemap.xml). 
How to setup page I need ? 
thank you!

**Comment by vezaynk** [comment]
If it gets interrupted, you can recover it from a temp file: https://github.com/vezaynk/Sitemap-Generator-Crawler/blob/358b6cc32e2ba5297df35d2c4079b2351fbf8797/sitemap.php#L81
