### ISSUE TITLE
How to exclude categories in Black List  

### ISSUE THREAD

**Issue by nickbazie** [viruzx/Sitemap-Generator-Crawler#12]
Hi @knyzorg 

Awesome script, thank you for it. 

Have a small question. How can I exclude some categories or IDs and everything that's inside? 
For example:" www.mysite/search-results?=" of "www.mysite/category1/"

P.S.: the black list only blocks one page. For example: it blocks /category1/ but doesn't block /category1/*

Cheers

**Comment by nickbazie** [comment]
Sorry, got it. 
All fine now. 

Thanks again for a fantastic and fast sitemap generator

**Comment by vezaynk** [comment]
Glad you appreciate my script! My latest update enables support for wildcards in the blacklist so now you can block that scans and indexing of all children of `www.mysite/category1/` by blacklisting `http://www.mysite/category1/*`. In the same fashion, you can blacklist all your search results with `http://www.mysite/search-results?=*`.

Have a nice day!

If this doesn't catch your use-case, drop me the link to the actual website so I can check it out.
