### ISSUE TITLE
Handle headers and body in a single request

### ISSUE THREAD

**Issue by vezaynk** [viruzx/Sitemap-Generator-Crawler#2]
Handling the last modified header is currently done in 2 requests instead of one. It should be reduced to a single one.

References: http://stackoverflow.com/questions/9183178/php-curl-retrieving-response-headers-and-body-in-a-single-request

**Comment by ghost** [comment]
#3 Updates the handling so it's done in one request.

**Comment by vezaynk** [comment]
@Z01DTech Doesn't work (reply in #3)

**Comment by vezaynk** [comment]
As I do not have sufficient knowledge of how the curl implementation for PHP works, I will leave it as is and hopefully someone will come along one day and continue this.

**Comment by mrl22** [comment]
Hi Guys,

I have now changed the code to pull the body and modified data in a single cURL request. I have created a pull request but you are also welcome to get it from here: https://github.com/webforward/Sitemap-Generator-Crawler

**Comment by vezaynk** [comment]
@mrl22 , great work as always!
