### ISSUE TITLE
mailto infinite recursion

### ISSUE THREAD

**Issue by zhornovy** [viruzx/Sitemap-Generator-Crawler#21]
I think you should check URL and skip it if it is a mailto link. If it finds mailto than it gets infinite recursion.
Example from my website
`[!] Found mailto://admin@myweb.com`
`[!] mailto://admin@myweb.com is relative, convert to absolute`
`[!] Result: https://myweb.com/news/mailto://mailto://mailto://...308 times more ....mailto://mailto://mailto://mailto://mailto://mailto://admin@myweb.com `

**Comment by vezaynk** [comment]
Will take a look at thia tonight

**Comment by vezaynk** [comment]
Fixed. I broke my own website at the time that I broke that. The idea of the a test suite is becoming more attractive by the day..
