### ISSUE TITLE
Do not overwrite sitemap.xml until complete

### ISSUE THREAD

**Issue by vezaynk** [viruzx/Sitemap-Generator-Crawler#27]
Currently, the sitemap.is written to disk on-the-fly. This produces invalid XML.

The sitemap should initially be written to a seperate file and then moved to replace the sitemap file.

**Comment by mangaflux01** [comment]
i re ran the sitemap with different output file this is what i get its generating xml as sitemap2.xml
![error](https://user-images.githubusercontent.com/31447036/29858773-6d7c25fc-8d78-11e7-90e1-6a25f1b3c7c2.png)

**Comment by vezaynk** [comment]
That is expected. The sitemap is wasn't not finished being generated. Fix coming soon.

**Comment by vezaynk** [comment]
Notes:

 - Temporary file will be stored as `$file.partial.xml`

 - PHP's `rename()` overwrites existing file

 - Backups/rotations are not necessary. 

Patch coming tonight!

**Comment by vezaynk** [comment]
I lied. <3 College

It's fixed. Closing.
