### ISSUE TITLE
Relative URLs fix

### ISSUE THREAD

**Issue by anatolinicolae** [viruzx/Sitemap-Generator-Crawler#28]
It looks like the tool doesn't consider query strings for relative URLs.

```
 [!] Checking index.php?case=pages&url=cookie 
 [!] index.php is relative, convert to absolute 
 [!] Result: index.php 
 [-] URL is not valid. Rejecting. 
```

**Comment by vezaynk** [comment]
Broken by #22, probably.

Do older versions work?

**Comment by vezaynk** [comment]
Mistake here: https://github.com/knyzorg/Sitemap-Generator-Crawler/blob/master/sitemap.php#L172

I improperly try to add a variable from parent scope. Fix coming tonight <3
