### ISSUE TITLE
Double entry

### ISSUE THREAD

**Issue by ghost** [viruzx/Sitemap-Generator-Crawler#35]
Command:
php sitemap.php file=sitemap.xml site=https://www.2globalnomads.info

Output:
> ...
> \<loc>https://www.2globalnomads.info/</loc>
> \</url>
> \<url>
> \<loc>https://www.2globalnomads.info/web-design-websites/</loc>
> \</url>
> \<url>
> \<loc>https://www.2globalnomads.info//</loc>
> ...

**Comment by vezaynk** [comment]
Refer to #33, just merged a fix

**Comment by ghost** [comment]
Works!
