### ISSUE TITLE
Does not crawl all pages.

### ISSUE THREAD

**Issue by aedelgod** [viruzx/Sitemap-Generator-Crawler#5]
When I ran this, it only indexed my menu, it didn't crawl into others like /top/2/

Example: http://www.mywebsiteisworth.xyz (/sitemap2.xml)

**Comment by vezaynk** [comment]
Can confirm bug. No idea what's wrong yet.
I'm very busy right now so I can't address this yet but it seems like some weird edge case.

Do note that this tool isn't perfect and based off a broken script which you can find here: https://www.plop.at/en/xml-sitemap.html version 2.0.

There is a version 3.0 out so you can try that in the meantime. Good luck!

I will address this bug when I can.

**Comment by mrl22** [comment]
I will have a look into this bug today and create a pull request once fixed.

**Comment by smurfiez** [comment]
Probably because of relative links instead of absolute links.

**Comment by mrl22** [comment]
aedelgod I have fixed this issue and have created a pull request for the author. On another note, you have pages named mywebsiteisworth.xyz/google.com with no slash on the end. This script is not intelligent enough to generate a sitemap on these pages and for now you will need to add "com" to the extension list in sitemap.php. I may look in future to develop the script to look at mime types.
https://github.com/webforward/Sitemap-Generator-Crawler

**Comment by vezaynk** [comment]
@mrl22 seems to have squashed it! Closing accordingly.
