### ISSUE TITLE
Why not a plugin?

### ISSUE THREAD

**Issue by rsm23** [viruzx/Sitemap-Generator-Crawler#50]
First of all I liked this package, but for dealing dealing with Laravel for more than 5 days I often find some difficulties when finishing a project and a client asks for a mechanism of a sitemap, there's many other Laravel packages for that but they all have some features that are not needed, this is simple way to achieve that and making it a Laravel package would help a lot.

**Comment by vezaynk** [comment]
I am unsure of how to package this for Laravel while keeping the script as a stand alone.

Either way, I believe that this would be out-of-scope for this repository. A fork integrating it with Laravel would be reasonable.

**Comment by vezaynk** [comment]
If anybody has a good argument in favor of this, please reopen this issue. If you do not have a good argument but want to see it happen, feel free to fork this project.

I am closing this issue.

**Comment by akiraz2** [comment]
May be you organize your beatiful script in Composer Package? I can do it, do you merge pr?

знаю что вы русский, не могли бы вы оформить ваш замечательный скрипт в виде пакета Composer . я бы сделал потом обертку для фреймворков. В принципе могу помочь оформить Composer package, но сможете ли вы оперативно принять Pull request?

**Comment by vezaynk** [comment]
If you can do it, go for it. I am fairly free this week so I can merge it quickly.
