### ISSUE TITLE
Adds only the main page :(

### ISSUE THREAD

**Issue by webapteka** [viruzx/Sitemap-Generator-Crawler#71]
Hello!

Sait https://www.indiamed.biz

Adds only the 1 main page :(

What could be the problem? What am I doing?

**Comment by vezaynk** [comment]
All your links start with `//` instead of `https://`. While this isn't incorrect per the web specification AFAIK, I don't see why you would do such a thing as I'm pretty certain that my parser isn't the only thing that it's breaking.
