### ISSUE TITLE
Crawling the root website instead of sub-root

### ISSUE THREAD

**Issue by yashitgarg** [viruzx/Sitemap-Generator-Crawler#72]
I assigned $site to 'https://docs.python.org/3/whatsnew/*'
But when I ran the script, it is crawling the root : docs.python.org/*
How can I force it to crawl URLs containing 'https://docs.python.org/3/whatsnew/' only ?

**Comment by vezaynk** [comment]
The purpose of a sitemap is to index the entire site, right? An earlier version featured a whitelist which could override the blacklist but I believe it has been removed as nobody found it useful and added needless complexities.

With that said, you can pull off something interesting using the blacklist to achieve what you want.

The blacklist uses `preg_match()` under the hood and as such you can use [this trick](http://php.net/manual/en/function.preg-match.php#103015) to make it only crawl your desired paths by blacklisting everything else.

Did github stop sending "new issue" emails? I never missed these before.

**Comment by siliconkibou** [comment]
Often a subfolder can be intended to be a separate site.  This is often done for targeting specific regions or countries... see apple.com, and apple.com/ca/, for instance.  It would be useful then to be able to crawl only apple.com/ca/ as a distinct site (as that's how it's viewed and submitted to Google, etc.

**Comment by siliconkibou** [comment]
Follow-up...an easy workaround is to modify sitemap.php to not force the $site to root, but changing this line:

$real_site = domain_root($site);

To this line:

$real_site = $site;

**Comment by vezaynk** [comment]
From my memory, it shouldn't have any adverse effects. Good catch.

So there we go, 2 methods to crawl a sub domain. Issue seems solved.
