### ISSUE TITLE
Please move the project away from GitHub

### ISSUE THREAD

**Issue by ghost** [viruzx/Sitemap-Generator-Crawler#74]
I just read that Microsoft is acquiring GitHub. I have seen enough of Microsoft love for open source for a life time to avoid everything that involves them. It is at best just a kiss of death and soon all users are required to install Microsoft malware and open Microsoft accounts to use GitHub, all all our information is for sale. I am quitting GitHub. So long and thanks for all the fish.

**Comment by vezaynk** [comment]
It has been over a month and microsoft has done no harm. I believe that Microsoft will know how to not squander a multi billion dollar acquisition and will instead focus on building stronger integrations.

I am currently a .NET Core developer and Microsoft has been very nice to me.  

I have an idle gitlab account just in case. We shall see where this takes us.
