### ISSUE TITLE
Little problems with &

### ISSUE THREAD

**Issue by webapteka** [viruzx/Sitemap-Generator-Crawler#75]
Hello!

I have url https://xn--80aknseecjj.xn--p1ai/reviews/index.php?act=id&msgid=1473770667.15

and in sitemap.xml a see:

https://xn--80aknseecjj.xn--p1ai/reviews/index.php?act=id&amp;msgid=1473770667.15

I put this url to browser and have a 404 error (((

How to fix this problem?

Thank you!

**Comment by vezaynk** [comment]
This is expected. XML does not allow & and they must be replaced with &amp;

Sitemap bots parse it properly.
