### ISSUE TITLE
Option to not crawl Frames

### ISSUE THREAD

**Issue by kewh** [viruzx/Sitemap-Generator-Crawler#79]
`<frame>` tags are crawled but as they are now deprecated and mostly blocked by modern browsers, it seems like a waste of processing time in the majority of cases, where the website is known not to use them. Could a config option be added to not crawl them? I'd be happy to add this.

**Comment by vezaynk** [comment]
It doesn't waste resources if they are not present. If it is, it should probably be enabled anyways. Just my thoughts.

**Comment by kewh** [comment]
But isn’t all of the HTML scanned a second time with the second call to the function get_links with the regex to look for frames. I assumed that doing a second scan would add to the runtime.

**Comment by vezaynk** [comment]
I mean yeah, it does. I doubt it's non negligible though. Most of the time is spent making network connections.

Maybe it does. Feel free to run some benchmarks.
