### ISSUE TITLE
[Feature Request] List all kinds of files & add an option to not try to curl some extensions

### ISSUE THREAD

**Issue by jean-christophe-manciot** [viruzx/Sitemap-Generator-Crawler#87]
@knyzorg 
First off, congratulations. Your solution is the most simple one out there allowing us to crawl & list all URLs of a website without being a rails/rake/ruby expert (many other solutions depend on them).

[My site](https://git.sdxlive.com) offer --among other thins-- some very fresh builds of many apt packages for several Linux distributions. The extensions of those files are:
- ```.deb``` 
- ```.ddeb```

If I run ```php sitemap.php``` (after configuring ```sitemap.config.php```), all the URLs ending with these extensions would be left out.

So I commented out the following lines of ```sitemap.functions.php```:
```
//    if (!$html) {
//        logger("Invalid Document. Rejecting.", 1);
//        return $depth--;
//    }
```

However, the crawler still tries to scan all these files; the problems are:
- they can be quite large 
- there are binary files

What should be done to have those URLs listed in the ```sitemap.xml``` without having the crawler download & inspect them?

**Comment by vezaynk** [comment]
Hey @jean-christophe-manciot,
Thanks for your kind words.

You should be able to use the $blacklist configuration variable to exclude the package files.
