### ISSUE TITLE
"mmap failed... cannot allocate memory"

### ISSUE THREAD

**Issue by tomjennings** [viruzx/Sitemap-Generator-Crawler#88]
Hi, thank you for the excellent script, it's been working great. I'm surprised at how few options there are out there to create sitemaps that are not hobbled with arbitrary restrictions.

I am having the following failure on a newly created URL (new site):
`mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 2149568512) (tried to allocate 2145390592 bytes) in /home/tomj/Bin/Sitemap-Generator-Crawler/sitemap.functions.php on line 208`

There's 103545 files on the site, all static simple files. Apache 2.4.25, on Debian 9.3.

(I also had to renice it, the default of -20 brought the (virtual) machine to a crawl...)

**Comment by tomjennings** [comment]
The URL causing the failure is http://warehouse.sr-ix.com/

**Comment by vezaynk** [comment]
Looks like you're hitting with an out-of-memory crash. It can only be fixed either through less memory usage, or more available memory.

As a user, the latter option is much easier. Try setting up swap memory: https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04
