### ISSUE TITLE
Add ability to exclude

### ISSUE THREAD

**Issue by ztheory** [viruzx/Sitemap-Generator-Crawler#9]
Having the ability to exclude certain files or folder would be lovely. Not usable for me until then :(

**Comment by vezaynk** [comment]
Exclude from the crawling or exclude from the indexing?

Crawling in the sense that none of it's links will be crawled either, while indexing means that it will be excluded but it's children will be crawled (unless specified otherwise).

**Comment by ztheory** [comment]
A fair question. I suppose my use case is crawling. Optimally I guess you'd want both to be offered.

**Comment by vezaynk** [comment]
Sorry for the delay, am very busy.

Will send out an update in a couple minutes

**Comment by vezaynk** [comment]
The is a new array option named `$blacklist`. It isn't indexed and isn't scanned.
