### ISSUE TITLE
Could not find files for the given pattern(s)

### ISSUE THREAD

**Issue by Jaydeep-01** [viruzx/Sitemap-Generator-Crawler#93]
I tried this crawler today, on the fist go it works fine, but when I run this second time without made any change it throws an error like this and not proceeding ahead.

INFO: Could not find files for the given pattern(s).
[+] Sitemap has been generated in 1.26 secondsand saved to sitemap.xml
[+] Scanned a total of 1 pages and indexed 0 pages.
[+] Operation Completed

how to resolve this ?

**Comment by vezaynk** [comment]
This looks unrelated to the script: https://www.google.com/search?q=%22info%3A+could+not+find+files+for+the+given+pattern%28s%29%22

The environment you're running it from is likely broken/missing dependencies.

**Comment by Jaydeep-01** [comment]
okay got it seems like something was wrong in the xampp. 😁
