### ISSUE TITLE
What if my website has more then 50,000 pages

### ISSUE THREAD

**Issue by Jaydeep-01** [viruzx/Sitemap-Generator-Crawler#95]
what if my website has more then 50,000 pages?

because as per Google SEO sitemap one sitemap not exceed 50,000 urls and 50 MB.

https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap#autositemap

so is this script is working by following this guidelines, by spitting the sitemaps, or create the new sitemap files after one xml file gets 50 MB or 50,000 urls?

**Comment by vezaynk** [comment]
This is a missing feature tracked in #43 

My priorities have been elsewhere lately, so I haven't gotten around to adding it in. If you're comfortable adding it in, I'd appreciate it! If not, this is something that can be handled in post-processing (I found [this](https://gist.github.com/kravietz/f2eec690ecb4dde84206) but haven't tested it).
