### ISSUE TITLE
Add a log with links, contains url returns 404

### ISSUE THREAD

**Issue by oim37** [viruzx/Sitemap-Generator-Crawler#99]
Hello,

It would be very convenient if you added the ability to log after creating the sitemap file. Some links on sites become outdated, content moves, and this is very useful information when you can see on which page the broken links are located.

As example:

```
404 - https://domain.tld/some/olddate-page/removed
      (found at https://domain.tld/about/agreement)
```

**Comment by vezaynk** [comment]
I'm no longer developing this, but 404s fall into this case: https://github.com/vezaynk/Sitemap-Generator-Crawler/blob/358b6cc32e2ba5297df35d2c4079b2351fbf8797/sitemap.functions.php#L364

which gets set here: https://github.com/vezaynk/Sitemap-Generator-Crawler/blob/358b6cc32e2ba5297df35d2c4079b2351fbf8797/sitemap.functions.php#L230

You're welcome to make the change and open a PR.

**Comment by oim37** [comment]
Thank you! 👍
